### ISSUE TITLE
在已勾选时间的token下仍弹出错误（如图

### ISSUE THREAD

**Issue by lucashirokuma** [Ostrichbeta/WHU-class-schedule-export-ics#9]
![C4C32046E88F69F3471F5FC1926868B3](https://user-images.githubusercontent.com/101861677/189525824-c1d6b8ff-51b1-476b-b0fd-75727ce2ac69.jpg)

**Comment by Ostrichbeta** [comment]
選擇週數後 按下確定了嗎？網頁課表是否已顯示週數？

**Comment by lucashirokuma** [comment]
按下确定了。在课表已显示周数的情况下仍提示“未选”
Ostrich_B ***@***.***>于2022年9月13日 周二20:02写道：

**Comment by lucashirokuma** [comment]
![wrong](https://user-images.githubusercontent.com/101861677/190115517-343daee1-2a73-4613-8a6e-8110760a8c5a.png)
